name: dec-latent-space
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - numpy=1.26
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
      - torch
      - umap-learn
